export const NAKSHATRAS = [
  { ta: 'அசுவினி', en: 'Ashwini' },
  { ta: 'பரணி', en: 'Bharani' },
  { ta: 'கார்த்திகை', en: 'Krittika' },
  { ta: 'ரோகிணி', en: 'Rohini' },
  { ta: 'மிருகசீரிடம்', en: 'Mrigashira' },
  { ta: 'திருவாதிரை', en: 'Ardra' },
  { ta: 'புனர்பூசம்', en: 'Punarvasu' },
  { ta: 'பூசம்', en: 'Pushya' },
  { ta: 'ஆயில்யம்', en: 'Ashlesha' },
  { ta: 'மகம்', en: 'Magha' },
  { ta: 'பூரம்', en: 'Purva Phalguni' },
  { ta: 'உத்திரம்', en: 'Uttara Phalguni' },
  { ta: 'அஸ்தம்', en: 'Hasta' },
  { ta: 'சித்திரை', en: 'Chitra' },
  { ta: 'சுவாதி', en: 'Swati' },
  { ta: 'விசாகம்', en: 'Vishakha' },
  { ta: 'அனுஷம்', en: 'Anuradha' },
  { ta: 'கேட்டை', en: 'Jyeshtha' },
  { ta: 'மூலம்', en: 'Mula' },
  { ta: 'பூராடம்', en: 'Purva Ashadha' },
  { ta: 'உத்திராடம்', en: 'Uttara Ashadha' },
  { ta: 'திருவோணம்', en: 'Shravana' },
  { ta: 'அவிட்டம்', en: 'Dhanishta' },
  { ta: 'சதயம்', en: 'Shatabhisha' },
  { ta: 'பூரட்டாதி', en: 'Purva Bhadrapada' },
  { ta: 'உத்திரட்டாதி', en: 'Uttara Bhadrapada' },
  { ta: 'ரேவதி', en: 'Revati' }
]
